spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    url: jdbc:sqlite:practice.db
    username: root
    password: 070211
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: JavaProject.Sqlite.global.config.SQLDialect

jwt:
  header: ${HEADER:Authorization}
  prefix : ${PREFIX:Bearer}
  secret-key: ${JWT_SECRET_KEY:dfhasjkdfhayffhdtyhdfkjfvfddkvnvssdvnknkknlnkdkmnlvknllnkknlvfdhydshghjkdfaskverafter}
  access-exp: ${JWT_ACCESS_EXP:10000}
  refresh-exp: ${JWT_REFRESH_EXP:604800}

logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace