spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    url: ${DB_URL:jdbc:mysql://15.164.26.179:3306/practice}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:070211}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true #sql 로그를 볼 수 있게 해줌
        format_sql: true #sql 로그를 예쁘게 포멧팅 해준다. (기존 show_sql만 작성해준다면 한줄로 로그가 나오지만 format_sql를 작성해준다면 줄바꿈이 됨)
        defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: 15.164.26.179
    port: 6379
    password: asdf

jwt:
  header: ${HEADER:Authorization}
  prefix : ${PREFIX:Bearer}
  secret-key: ${JWT_SECRET_KEY:dfhasjkdfhayffhdtyhdfkjfvfddkvnvssdvnknkknlnkdkmnlvknllnkknlvfdhydshghjkdfaskverafter}
  access-exp: ${JWT_ACCESS_EXP:10000}
  refresh-exp: ${JWT_REFRESH_EXP:604800}

logging:
  level:
    com.example : DEBUG #패키지 내의 모든 클래스에 대해 로깅 수준을 DEBUG로 설정
    #
    org:
      hibernate:
        type:
          descriptor:
            sql: trace #hibernate이 보여주는 로그에 있는 ?에 어떤 값이 들어갔는지 구체적으로 알고 싶을 때 사용하는 옵션
chatgpt:
  api-key: ${OPEN_AI_KEY:asdfghjkl}
